services:
  db:
    image: postgres:16
    container_name: patient_db
    environment:
      POSTGRES_PASSWORD: patient_pass
      POSTGRES_USER: patient_user
      POSTGRES_DB: patient_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: patient_backend
    environment:
      DB_USER: patient_user
      DB_PASS: patient_pass
      DB_NAME: patient_db
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db


  frontend:
    image: nginx:alpine
    container_name: patient_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend
